services:
    server:
        build: .
        image: telegram-fwd
        container_name: telegram-fwd
        restart: unless-stopped
        volumes:
            - type: bind
              source: ./config.toml
              target: /config.toml
            - type: bind
              source: ./session.bin
              target: /session.bin

networks:
    default:
        name: nginx
        external: true
